### ISSUE TITLE
it does not work

### ISSUE THREAD

**Issue by jamatou** [elfarsaouiomar/monitor-new-subdomain#1]
Hi Omar,
great work. I install it, but it doesn't work.
![Capture](https://user-images.githubusercontent.com/45011146/123854758-67958d80-d91f-11eb-83d6-de9e00572c27.PNG)

**Comment by elfarsaouiomar** [comment]
Hi, thank you for your report.

Just make sure to set telegram chat id if you want to receive notifications via telegram otherwise set double-quotes.

Fix in  [commit](https://github.com/elfarsaouiomar/monitor-new-subdomain/commit/07d9f26c945a8e630f6b83e6b9b785a38d463a9c)

happy hacking !
