### ISSUE TITLE
Notify integration?

### ISSUE THREAD

**Issue by g0lr** [elfarsaouiomar/monitor-new-subdomain#11]
Is viable a integration with notify?

**Comment by elfarsaouiomar** [comment]
Hello @g0lr,

Here medium blog on how to set up a telegram bot:
* https://medium.com/javarevisited/sending-a-message-to-a-telegram-channel-the-easy-way-eb0a0b32968

Here is a blog on how to set Incoming webhooks for Slack
* https://sankalpit.com/plugins/documentation/how-to-create-slack-incoming-webhook-url/

Happy Hacking

**Comment by elfarsaouiomar** [comment]
Hello @g0lr ,

unfortunately, we don't viable an integration with notify?
I'm going to close this issue if have another question feel free to open a new issue or re-open this one.

#Happy_Hacking
