### ISSUE TITLE
Error while running in ubuntu

### ISSUE THREAD

**Issue by channyein1337** [elfarsaouiomar/monitor-new-subdomain#18]
Hi,

May I know how can I fix this error "[!] Expecting value: line 1 column 1 (char 0)" ?

![image](https://user-images.githubusercontent.com/45043329/212620928-e1174b0d-5d09-4e14-93d0-5d9196bf6b92.png)

**Comment by elfarsaouiomar** [comment]
Hey @channyein1337 

Thanks for let me know about this issue.
Fix in PR https://github.com/elfarsaouiomar/monitor-new-subdomain/pull/19

Happy Hacking 🔥
