### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Krosskid12** [elfarsaouiomar/monitor-new-subdomain#5]
![image](https://user-images.githubusercontent.com/73221787/142162744-33455370-1a99-4501-a534-c3a986a9b8d8.png)
Thanks in advance.

**Comment by Krosskid12** [comment]
> Hello,
> 
> Change the `dbHost` in Config.py to 127.0.0.1 dbHost="127.0.0.1"

Thanks man.Anyway to run it 24/7 in vps?

**Comment by elfarsaouiomar** [comment]
> Thanks man. Anyway to run it 24/7 in VPS?


Hello,

you can use cron job,
0 */5 * * * python3 /root/monitor-new-subdomain/check-new-subdomain.py -m -t
