### ISSUE TITLE
Failed to connect to the mongodb

### ISSUE THREAD

**Issue by kesonn** [elfarsaouiomar/monitor-new-subdomain#6]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/36539433/153563848-45bc531c-35f7-486d-939b-57f404eebf77.png">

**Comment by elfarsaouiomar** [comment]
Hello Thank you for using this tool,
Can please provide other information?
* what command did you run?
* Is there any error on the console
* Do you use Docker Container?

**Comment by kesonn** [comment]
I used docker on my MacBook Pro.
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/36539433/155269501-64ec4b71-3871-4811-85f1-be5b492acff9.png">

Then, connection to localhost:27020 is sent to port 27017 in the container.
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/36539433/155270245-029827e4-75f9-4b84-abfd-f9a7128a9817.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/36539433/155270273-b2429e2b-1eb8-4059-a244-11cb8670832e.png">

**Comment by elfarsaouiomar** [comment]
Hello @kesonn,

make sure to run the script first after that you will be able to access the database. 
run the following command: ```docker-compose run mns  -a domain.com```
